### PR TITLE
Add a dict-like get method

### PR DESCRIPTION
**Pull request by craiga**
Hey, I really appreciate this library! It was exactly what I needed to parse a very large JSON file from eBay. Thanks so much for putting it on PyPI!

I'm not sure if contributions are welcome (or if this is a good idea), but I found myself wishing for a dict-like get method when dealing with JSON data, so I've added one here.

[There are a bunch of other dict methods which could be added](https://docs.python.org/3/library/stdtypes.html#dict), which I might have a go at in time if you think this is a good idea?

### CODE REVIEW

**Comment by daggaz** [comment]
Hey, sorry for the slow reply. Yeah, this is a good idea - though I appear to have created a merge conflict for your PR.

If you want to add any other dict-like methods, I'd be happy to look at them too.

**Comment by pyves-hs** [comment]
Great library indeed, @craiga and @daggaz I am also interested in this feature, any eta to get it in?

**Comment by craiga** [comment]
No problem @daggaz; I've just resolved those conflicts.

**Comment by daggaz** [comment]
I finally merged this, no idea why I took so long...

**Pull request merged**
